How do we use numpy library?

In [1]:
import numpy as np # np - Alias name of numpy


In [2]:
distance = [10,15,17,26]
time = [0.30,0.47,0.55,1.20]


In [3]:
my_list =[101,102,103,104]
print(type(my_list))

<class 'list'>


In [4]:
my_ndarray = np.array(my_list) # Creating a numpy array 

print(type(my_ndarray))
print(my_ndarray)

<class 'numpy.ndarray'>
[101 102 103 104]


In [5]:
nd_distance =np.array([10,15,17,26])
nd_time = np.array([0.30,0.47,.55,1.20])

In [6]:
print(type(nd_distance))
print(type(nd_time))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
nd_speed = nd_distance/nd_time
print(nd_speed)

[33.33333333 31.91489362 30.90909091 21.66666667]


From the above,We could infer that Numpy supports element wise operation

### Attributes of ndarray

---- ndim,shape,size,dtype

----- Attributes are the ones that you can use to get to know about of a ndarray(numpy array)

# We are trying to create a numpy array from a list of lists... 



In [8]:
np_city = np.array([["Delhi","Mumbai","Banglore","Chennai"], ["Kolkata","Hyderabad","Vishakhapattnam","Chennai"]])

In [9]:
np_city.ndim # used to find out the number of dimensions of the numpy array

2

In [10]:
np_city.shape # Shape attribute returns the no of rows and columns present in the numpy array in the form of tuple

(2, 4)

In [11]:
np_city.size # It returns total no of elements present in the numpy array.

8

In [12]:
np_city.dtype # <U15 maximimum no of character which is present in vizag name.

dtype('<U15')

In [13]:
np_city1 = np.array(["Delhi","Mumbai","Banglore","Chennai"])

In [14]:
np_city1.ndim # Attributes do not end with ()

1

In [15]:
distance_1 = np.array([10,12,15,17,20]) 

distance_2 = np.array([100,200,300,400,500])

time = np.array([0.3,0.45,0.25,0.5,0.16])



In [16]:
sum_distances = distance_1 + distance_2

In [17]:
print(sum_distances)

[110 212 315 417 520]


In [18]:
distance_1 | distance_2

array([110, 204, 303, 401, 500], dtype=int32)

## Broadcasting

In [19]:
print(distance_1)

[10 12 15 17 20]


In [20]:
distance_1*2 # the numpy array is multiplied with a single scalar value.

array([20, 24, 30, 34, 40])

In [21]:
distance_1/5 # In case of numpy array the value gets broadcasted.

array([2. , 2.4, 3. , 3.4, 4. ])

In [22]:
distance_1 +3

array([13, 15, 18, 20, 23])

In [23]:
distance_1 -10

array([ 0,  2,  5,  7, 10])

# How to access array elements using Indexing?

In [24]:
dist_covered = np.array([[2,4,6,8],[3,6,9,12]])

print("The distance covered by two cars in 4 different rides are:  ")

print("------------------------------------------------------------")
print(dist_covered)

The distance covered by two cars in 4 different rides are:  
------------------------------------------------------------
[[ 2  4  6  8]
 [ 3  6  9 12]]


In [25]:
dist_covered[0,0]

2

In [26]:
dist_covered[0] # This would retrieve all the values of row 1

array([2, 4, 6, 8])

In [27]:
dist_covered[1,2]

9

In [28]:
dist_covered[1,1:]

array([ 6,  9, 12])

In [29]:
dist_covered[:,2:] # index num: ---> Select all the values the specified index value 

array([[ 6,  8],
       [ 9, 12]])

In [30]:
dist_covered[:,0:2] # 0:2 --> 0 is the start index so its is inclusive.
                    # 2 is the end index so it is inclusive only until 2-1 =1 
    # Hence,the values present in the first and second columns are retrieved.

array([[2, 4],
       [3, 6]])

In [31]:
dist_covered[:,:2] # :2----> Selecting all the values until (2-1) in the column which means that only the values present in the 0th & 1th columns of both the rows would be retrieved.

array([[2, 4],
       [3, 6]])

# Conditional Selection

In [32]:
dist_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [33]:
dist_covered > 5 #Whenever you use comparision operator on numpy arrays, it would always return boolean set of values.

array([[False, False,  True,  True],
       [False,  True,  True,  True]])

In [34]:
dist_covered[dist_covered> 5] # within  the square braces instead of the index,if you pass the condition,it is called "conditional selection"

array([ 6,  8,  6,  9, 12])

In [35]:
dist_covered[dist_covered== 6] # equal to condition

array([6, 6])

In [36]:
dist_covered[dist_covered== 6].size # this would give you the number of rides had covered exactly 6 km.

2

In [37]:
dist_covered[dist_covered >= 6] # Greater than or equal to

array([ 6,  8,  6,  9, 12])

In [38]:
dist_covered[dist_covered >= 6].size

5

In [39]:
print('The total no of rides in which the total distances covered is not equal ro 6 kms is:   ')
dist_covered[dist_covered != 6].size

The total no of rides in which the total distances covered is not equal ro 6 kms is:   


6

In [40]:
dist_covered[(dist_covered < 6) & (dist_covered>3)] # Using logical & comparision operators

array([4])

In [41]:
dist_covered[~(dist_covered < 6)] # making use of logical not operator

array([ 6,  8,  6,  9, 12])

# Universal Functions -Ufunc

In [42]:
num_array = np.array([4,9,16,25,36])

In [43]:
print("Square root of the num_array values are : ")
print(np.sqrt(num_array))

Square root of the num_array values are : 
[2. 3. 4. 5. 6.]


In [44]:
print("Average(mean) value of the num_array is: ")
print(np.mean(num_array))

Average(mean) value of the num_array is: 
18.0


In [45]:
print("standard Deviation of the num_array is: ")
print(np.std(num_array))

standard Deviation of the num_array is: 
11.436782764396638


In [46]:
print("Variance of the num_array is: ")
print(np.var(num_array))

Variance of the num_array is: 
130.8


In [47]:
print(np.sum(num_array))

90


In [48]:
print(np.median(num_array))

16.0


In [49]:
num_array2 = np.array([1.75,2.6,3.4])

Say,We want to round off the values.We can do that either using the floor or ceil function

In [50]:
np.floor([num_array2]) # The values are floored down to the nearest previous numbers

array([[1., 2., 3.]])

In [51]:
np.ceil([num_array2]) #The values are ceiled up to the nearest next numbers...

array([[2., 3., 4.]])

# Shape Manipulation

---> Flatten the array,resize the array,how to stack the array,reshape the array

In [52]:
dist_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [53]:
dist_covered.shape

(2, 4)

In [54]:
dist_covered.ravel() # This method is used to flatten the array to a 1-dimentional array.

array([ 2,  4,  6,  8,  3,  6,  9, 12])

Kindly Remember that what you seeabove is just a view of what the ravel( )method could do.

In [55]:
dist_covered.ravel().ndim

1

In [56]:
dist_covered.reshape(1,8)

array([[ 2,  4,  6,  8,  3,  6,  9, 12]])

In [57]:
dist_covered.reshape(4,2) # reshape does not affect the original array..

array([[ 2,  4],
       [ 6,  8],
       [ 3,  6],
       [ 9, 12]])

In [58]:
dist_covered.resize(2,4) # resize affects the original array..

In [59]:
dist_covered

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

# How to split the numpy array?

--hsplit,vsplit

In [60]:
np.hsplit(dist_covered,2) # Split the array column wise...3 Will not work as only 4 columns are there


[array([[2, 4],
        [3, 6]]),
 array([[ 6,  8],
        [ 9, 12]])]

In [61]:
 # np.hsplit(dist_covered,3)

We can infer from above that hsplit only equal sized sub-arrays..

In [62]:
np.vsplit(dist_covered,2) # Split the array along the row...

[array([[2, 4, 6, 8]]), array([[ 3,  6,  9, 12]])]

# Stacking the values-hstack & vstack..

In [63]:
print(dist_covered)
print("------------")
dist_covered3 = np.array([[1,2,3,4],[15,16,17,18]])

print(dist_covered3)
print("------------")


[[ 2  4  6  8]
 [ 3  6  9 12]]
------------
[[ 1  2  3  4]
 [15 16 17 18]]
------------


In [83]:
print("The Stacked arrays using hstack: ")
print(np.hstack((dist_covered,dist_covered3)) #hstack adds the number of columns

SyntaxError: unexpected EOF while parsing (Temp/ipykernel_10576/816154439.py, line 2)

In [66]:
dist_covered2 = np.array([[2,4,6,8],[3,6,9,12],[1,2,3,4],[16,16,17,18]])
dist_covered2

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 1,  2,  3,  4],
       [16, 16, 17, 18]])

In [67]:
#print(dist_covered)
#print("------------")


#print(dist_covered2)
#print("------------")
#np.hstack((dist_covered,dist_covered2)) # hstack is not possible because the number of rows is not

Will vstack be possible? **Yes**

In [68]:
print("The Stacked arrays using vstack: ")
print(np.vstack((dist_covered,dist_covered2))) #vstack adds the number of rows

The Stacked arrays using vstack: 
[[ 2  4  6  8]
 [ 3  6  9 12]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 1  2  3  4]
 [16 16 17 18]]


As it maintain the same no of columns & increases the no of rows.Therefore,vstack is possible.

# Generating numpy arrays using inbuild numpy methods...

---- arange,linspace,randint,randn,rand

**arange** 
-- Return evenly spaced values within a given interval as input

In [69]:
np.arange(0,20) # by default this method would generate integer value.
                # by default,arange generates equally spaced values with an interval of 1..
                # Always the end limit value is inclusive only until(end limit - 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [70]:
np.arange(0,20 ,dtype = "float")

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [71]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [72]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [73]:
np.arange(0,20,2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

linspace

--- Return evenly spaced numbers over a specified interval..

In [74]:
np.linspace(1,10,5) # Both start & stop limit are inclusive.

                    # 3rd parameter here, specifies the no of values to be generated within the given start & stop limits.

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [75]:
np.linspace(0,20,100)

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

We can from the above that linspace has generated 100 equally spaced value within the limit (0,20)

In [76]:
np.linspace(1,10,5, dtype = "int")

array([ 1,  3,  5,  7, 10])

# How to generate Random Arrays using Numpy Methods?

rand

Create an array of the given shape & populate it with random variable derived from uniform distribution between (0,1)

In [77]:
np.random.rand(3,2)

array([[0.97128441, 0.78649991],
       [0.68744699, 0.97872715],
       [0.19095822, 0.17153464]])

 randn

Return a variable (or a set of variables) from the "Standard Normal" Distribution,Unlike rand which is form a uniform distribution:

    
A Standard Normal distribution has mean 0 and SD if 1 as we know.

In [78]:
np.random.randn(5)

array([ 1.23725128, -0.1744934 , -1.85679034, -0.80557508, -0.43960593])

In [79]:
np.random.randn(3,2)

array([[-1.33546182,  0.55279245],
       [ 1.02250202,  1.15010182],
       [ 2.05190751,  1.14365475]])

randint

--- Return random integers from low(inclusive) to high(exclusive)

In [80]:
np.random.randint(5,20) # Will gererate any random number between 5 & 20.

19

In [81]:
np.random.randint(5,20,3)# Will gererate any three random number between 5 & 20.

array([11, 14,  6])

In [82]:
np.random.randint(20,50,10)

array([27, 27, 35, 24, 25, 40, 22, 37, 41, 29])

# End OF Numpy discussion...